### ISSUE TITLE
Items are permanently lost sometimes when you die

### ISSUE THREAD

**Issue by LyonGalaxy** [LunaPixelStudios/Fear-Nightfall#1]
### Describe the Bug

Corpse dissapears/doesn't generate when dying

### Reproduction Steps

1. Make a World
2. Play for a while
3. Die multiple times
4. Sometimes there isn't a corpse with your items in the place you died and you lose all your items
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Fear Nightfall v2 HF

**Comment by NathanRMS1** [comment]
This also happened with me when I was playing on a server with my friends.
I was exploded by a creeper and my friend died by my side due to the bamboo spikes, but my corpse wasn't anywhere. I even searched for entities with F3+B but no cigar.
Thought it was something about the spikes, but corpses could be found there when people died.

**Comment by LyonGalaxy** [comment]
> This also happened with me when I was playing on a server with my friends. I was exploded by a creeper and my friend died by my side due to the bamboo spikes, but my corpse wasn't anywhere. I even searched for entities with F3+B but no cigar. Thought it was something about the spikes, but corpses could be found there when people died.

Yes, i've tried multiple ways of dying, so far, every death i've tried has a chance of not spawning your corpse.

**Comment by SHXRKIIE** [comment]
Nothing should be affecting your corpse, not even a creeper blowing it up. A corpse only disappears when the items are taken out of it.
