### ISSUE TITLE
Unable to use Essential Mod

### ISSUE THREAD

**Issue by Haybbale** [LunaPixelStudios/Fear-Nightfall#11]
### Describe the Bug

Error 805 with essential mod cant fix using 16GB+ of ram?

### Reproduction Steps

I only try to open the modpack through Curseforge and I make sure to allocate nearly all of my memory (I only like to use 75% max for mods) to even try to get it to work. I added essential mod so that I could possibly play with my friends but every time I try to open it with that it crashes?

Is there any way to use essential launcher with this mod? Or do I have to pay for a server to be able to play with friends? 

Thanks 

### Crash Report or Log

805

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Fear Nightfall v5

### Other Mods

Essential Mod
https://essential.gg/en/

**Comment by SHXRKIIE** [comment]
Our modpacks don't support any mods that add singleplayer hosting / world sharing because we already provide free world sharing. The "Essential" mod is therefore incompatible.

To share your world using our own world hosting, click the "Open to Lan" or "Share World" button in the game menu when in a singleplayer world, and share the world.

It will give you an address, like magma-cube.mc.lunapixel.gg, which your friends can use to connect directly to your world as if it were a server!

We still highly suggest not to play through LAN as LAN is untested and unreliable. Using it will cause longterm damage to your world.

There is no reason to use LAN, as we support both paid and free methods of hosting a server the normal way.

**Comment by nervehammer1** [comment]
Luna servers fucking suck.

**Comment by swat37** [comment]
Delete Luna-FORGE-MC1.19.X-1.0.1.jar and FancyHotbar-Fabric-1.0.0.jar in the mods folder
