### ISSUE TITLE
No monsters spawning

### ISSUE THREAD

**Issue by Manu-SKL** [LunaPixelStudios/Fear-Nightfall#138]
### Describe the Bug

After playing a few days (Minecraft days) monsters stop spawning like im playing peaceful mode. The only mob that spawns is Siren Head.
Creating a new map seems to fix the bug for another few days (Minecraft days)
The number of days seems to be random on some maps it takes just 2 to 3 days and some other maps it takes a lot longer.

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

17.5 Hf

**Comment by chorbintime** [comment]
What launcher did you use to install modpack?

**Comment by Manu-SKL** [comment]
TLauncher

**Comment by chorbintime** [comment]
TLauncher is known spyware and is also unable to install mods or modpacks correctly. Because we offer no support for piracy due to Discord TOS, you will need to provide proof you own a legitimate copy of Minecraft or leave the server. For a safe, working way to install both mods and modpacks, read the ⁠⁠faq guide on installing modpacks.

**Comment by Manu-SKL** [comment]
This is not about piracy or the launcher. The problem is server side. I'm not playing single.
