### ISSUE TITLE
JER missing tabs or tabs bug out

### ISSUE THREAD

**Issue by InFuRiTy** [LunaPixelStudios/Fear-Nightfall#143]
### Describe the Bug

Mob drops tab doesn't show up when connected to servers or Lan worlds but works fine in single player worlds.
Same goes for other JER tabs as well like ore gen.

These issues were tested out with and without our mod additions. Same results in each case.

### Reproduction Steps

1. Join a server or lan world
2. Search for an item that's dropped my mobs
3. Mob tab doesn't show up
...

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v1.0.2

### Other Mods

 Extra Client mods: Xaeros minimap+map, ftb chunks, Inventory HUD+, OAth.(<-personal preferences but other players reported having the same issues to us without these mods)
 Extra Server mods: Server Vein miner, ftb chunks, ftb essentials, Dark timer (item cleaner), Discord chat relay.
 Pack mods removed: Localized Chat (request by our players)

**Comment by nvb-uy** [comment]
We don't offer support to modified versions of the modpacks as we cannot guarantee that the modpack works properly after you've done modifications. Please modify the modpack at your own risk.

This might be caused by a bad server installation, please read the selfhosting guide: https://github.com/chorbintime/LPS-readme/wiki
