### ISSUE TITLE
Lag when you look to the Altar of hexerei mod

### ISSUE THREAD

**Issue by TimoonD** [LunaPixelStudios/Fear-Nightfall#23]
### Describe the Bug

Hello, the game is very laggy when you look after the hexerei altar but only when you look directly at it.
The Mahogany one is very laggy, the willow one and witch hazel version is laggy but you can play with.

Many thanks in advance
i really love your modpack !! Thanks for this

### Reproduction Steps

1. put the altar
2. look at the altar
3. feel the lag
...

### Screenshots and Videos

https://github.com/LunaPixelStudios/Fear-Nightfall/assets/151016809/3ff55dd8-ae5c-4587-b07c-fcec2b95b4c1

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v8

**Comment by SHXRKIIE** [comment]
Ill see if i can figure out the cause

**Comment by jchung01** [comment]
Caused by "The Man From the Fog" mod, you can see the spark profile [here](https://spark.lucko.me/mnDGcAFMqq?hl=2059,2191). Removing/disabling the mod fixes the render lag when looking at the altar. Haven't tested 0.2.1c of the mod though.

**Comment by SHXRKIIE** [comment]
Yeah just did that myself, remove that mod

**Comment by WilliamFancyFace** [comment]
Hey! I'm experiencing the same issue. As of today, the spark profile you linked doesn't work.
![image](https://github.com/user-attachments/assets/a689ec92-dc00-4f69-808c-f41763895e5d)
Given that only one .jar file with spark in its name was in the mods folder, I moved it out of the mods folder for Fear the Nightfall, and placed it in D > curseforge > minecraft > New Folder. After relaunching the game, the mahogany alter still drastically drops my frames when I look at it.
Anyone think they can find out what's changed between Nov 20, 2023 and Oct 18, 2024 that keeps this bug in the game even after the spark .jar has been removed, or am I mistaken somehow? Did I move the wrong mod, is it still being loaded because I just moved it out of the Instances folder but not out of the curseforge folder?

**Comment by Aethdae** [comment]
Since running into the same problem, I ran my own profiler to see the cause. For us it was the Siren Head mod. No frame drops after removing it. Add spark back to the folder and get an admin to run the profiler while looking at the block to confirm.
