### ISSUE TITLE
Getting hardstuck in caves

### ISSUE THREAD

**Issue by AP0PU** [LunaPixelStudios/Fear-Nightfall#38]
### Describe the Bug

Seemingly at random, the game will pull the player inescapably towards a random block in the world. This is literally game breaking and cannot be escaped.

### Reproduction Steps

1. Walk through caves until bug is encountered
2. The bug only seems to have effect in survival

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v10

**Comment by jadonbp** [comment]
This is caused by Infected Evokers as referenced in case #33. The mob will pull you towards them if you're close enough regardless of any obstacles. You can escape this by using a flying broom from the Hexerei mod or by despawning the mob by toggling the game difficulty to peaceful and then back to whatever you had it set as before.
