### ISSUE TITLE
frozen screenload

### ISSUE THREAD

**Issue by ISnowy23** [LunaPixelStudios/Fear-Nightfall#64]
### Describe the Bug

this loading screen  doesnt go away when starting the world
i can hear how i break blocks and mobs, also how i die

### Reproduction Steps

1.install modpack normally
2.create a world
3.the loading screen appears
4. loading screen doesnt go away, but the game woeks, i can move, breack blocks and mobs can kill me

### Screenshots and Videos

![imagen_2024-01-29_142749607](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/158093033/d285f662-28b1-4b61-9798-bb040f57cd11)

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

### Other Mods

there is nothing else, apart from modpack fear nightfall

**Comment by chorbintime** [comment]
please send your latest.log in the logs folder

**Comment by Wolphyxx** [comment]
I have the same issue (with curseforge), and now i try it with ATLauncher (some mods weren't able to be downloaded for some reason), and i wait for it while I write this. With curseforge i waited for like 40min, it didn't go away. Also, when i wait for it ('cause i tried multiple times) and i go to another window, when i get back to my minecraft window, it lags, like i see the Mojang logo when loading a texturepack and the loading screen just flashing out. Idk, i update my driver 'cause of this, still doesn't work on CurseForge. Btw, i write at the same time as my world trying to load, and when I went back to the minecraft window (on ATLauncher) it flashes again, but between a black screen and the loading screen(which says "validating selected data packs").

I also i play on a laptop, i have a real minecraft account, and i had trouble with the booting system recently(like a month before the day i write this). When i try to play the modpack, doesn't matter the launcher, my CPU is 100% loaded, my memory too, and the GPU isn't loaded at all (maybe because i still have issues with it since the booting problem).

I hope you find this useful, man idk what to do now, i really want to play this modpack.
Have a great day
-Wolphyxx

**Comment by Wolphyxx** [comment]
I also can't play it, 'cause i don't hear anything. The guy who created this issue said that he can play it without seeing it, so he hears the mobs i guess, but i don't. I don't if this helps but when i close the window ('cause i'm stuck on the loading screen) and then i relaunch the modpack, i have a world that is created. When i join it i have the same issue
-Wolphyxx

**Comment by Wolphyxx** [comment]
And i have windows 11, i only use the fear nightfull, and it doen't crash the game if you are wondering.

**Comment by Wolphyxx** [comment]
Oh, i made a new world, which i named "try1", and after i denied the "end program" i managed to go past the loading menu, but still, it was flashing between the game and a black screen (the game was only my crosshair, my hotbar with hearts and hunger, the fps info, and "1 heart" written above my hotbar). I tried it again, it failed. i tried making a new world, same problem, and when i was takiing a pic, it just crashed

**Comment by Wolphyxx** [comment]
![Capture d'écran 2024-01-31 203930](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/158213022/07444a73-8f9b-4e48-a6eb-729747010fc5)
After tries and tries, it just doesn't work

**Comment by chorbintime** [comment]
I can't help if nobody sends a latest.log

**Comment by GreatLordMagus** [comment]
i have this exact problem !! so disapointing as i switched from bedrock on console to java on pc only to play this mod !!! help me to find a solution plz

**Comment by GreatLordMagus** [comment]
you said you needed a latest.log, i found where it is but tell me wich one to select
![Capture d’écran 2024-02-01 231228](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/158540626/f63a929d-fab7-4b06-b7ae-4ffea144e346)

**Comment by chorbintime** [comment]
You need to use a modded launcher such as ATLauncher to install and play modpacks. Do not install modpacks into your .minecraft directory.

**Comment by GreatLordMagus** [comment]
I'm currently using curseforge and the game freeze exactly at the same place as seen on ISnowy23 picture

**Comment by GreatLordMagus** [comment]
you said you need a latest.log to help, i found the location of minecraft logs on my computer but i don't know wich one to open

**Comment by chorbintime** [comment]
send the one that is named "latest"
