### ISSUE TITLE
Performance Guide fuc-ing up my computer

### ISSUE THREAD

**Issue by Magician-Dev** [LunaPixelStudios/Fear-Nightfall#80]
### Describe the Bug

I opened up Fear Nightfall with the Curseforge Minecraft Launcher and it took like 10 minutes to go to the main menu (i considered that normal because my computer has an i3 8100U or something like that with integrated graphics) and i pressed the "Performance Guide" button. Then, the game froze, but it didn't crash because the music kept playing. I tried everything: Ctrl Alt Del, Alt + F4, Spam clicking to get the close program popup and nothing worked. I had to hard reset my PC.

### Reproduction Steps

1. Open up Fear Nightfall with similar system specs
2. Press the Performance Guide button
3. Let it crash

This may or may not be a cant-reproduce case.

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

### Other Mods

None

**Comment by chorbintime** [comment]
The performance guide button simply opens up https://rpg.prominence.wiki/performance-guide on your current web browser. If this caused your game to freeze, its because you allocated too much RAM to the game or did something else to make it run poorly. The modpack only takes a minute at most to launch - 10 minutes means you did something wrong. Because of this, your PC probably did not have the hardware power necessary to open the link in a web browser.
